In [ ]:
!pip install -q kaggle

In [ ]:
!mkdir ~/.kaggle

In [ ]:
!cp kaggle.json ~/.kaggle

In [ ]:
!kaggle datasets download -d sayanroy058/fossil-image

 99% 541M/544M [00:07<00:00, 37.2MB/s]
100% 544M/544M [00:07<00:00, 72.4MB/s]


In [ ]:
!unzip /content/fossil-image.zip

Archive:  /content/fossil-image.zip
  inflating: Geo Fossils-I Dataset/Ammonites/Ammonite1.jpg  
  inflating: Geo Fossils-I Dataset/Ammonites/Ammonite10.jpg  
  inflating: Geo Fossils-I Dataset/Ammonites/Ammonite100.jpg  
  inflating: Geo Fossils-I Dataset/Ammonites/Ammonite101.jpg  
  inflating: Geo Fossils-I Dataset/Ammonites/Ammonite102.jpg  
  inflating: Geo Fossils-I Dataset/Ammonites/Ammonite103.jpg  
  inflating: Geo Fossils-I Dataset/Ammonites/Ammonite104.jpg  
  inflating: Geo Fossils-I Dataset/Ammonites/Ammonite105.jpg  
  inflating: Geo Fossils-I Dataset/Ammonites/Ammonite106.jpg  
  inflating: Geo Fossils-I Dataset/Ammonites/Ammonite107.jpg  
  inflating: Geo Fossils-I Dataset/Ammonites/Ammonite108.jpg  
  inflating: Geo Fossils-I Dataset/Ammonites/Ammonite109.jpg  
  inflating: Geo Fossils-I Dataset/Ammonites/Ammonite11.jpg  
  inflating: Geo Fossils-I Dataset/Ammonites/Ammonite110.jpg  
  inflating: Geo Fossils-I Dataset/Ammonites/Ammonite111.jpg  
  inflating: Geo Fossil

In [ ]:
import os
import shutil
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
import shutil
from sklearn.model_selection import train_test_split
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.models import Model
from keras.optimizers import Adam
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.models import Model
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
from tensorflow.keras.preprocessing.image import load_img, img_to_array

### Deleting a folder

In [ ]:
"""import os
import shutil

folder_to_delete = "/content/Geo Fossils-I Dataset"

# Use shutil.rmtree to delete the folder and its contents
shutil.rmtree(folder_to_delete)

# Verify that the folder has been deleted
try:
    print(os.listdir(folder_to_delete))
except FileNotFoundError:
    print(f"The folder {folder_to_delete} has been successfully deleted.")"""

'import os\nimport shutil\n\nfolder_to_delete = "/content/Geo Fossils-I Dataset"\n\n# Use shutil.rmtree to delete the folder and its contents\nshutil.rmtree(folder_to_delete)\n\n# Verify that the folder has been deleted\ntry:\n    print(os.listdir(folder_to_delete))\nexcept FileNotFoundError:\n    print(f"The folder {folder_to_delete} has been successfully deleted.")'

In [ ]:
import os

# Define the current folder name and the new folder name
current_folder_name = '/content/Geo Fossils-I Dataset'
new_folder_name = '/content/Geo_Fossil_Dataset'

# Use os.rename() to change the folder name
os.rename(current_folder_name, new_folder_name)

In [ ]:
import os
import shutil
from sklearn.model_selection import train_test_split

# Define the path to your original image dataset
dataset_path = '/content/Geo_Fossil_Dataset/'

# Define the paths for the train, test, and valid folders
train_path = '/content/train'
test_path = '/content/test'
valid_path = '/content/valid'

# Create the train, test, and valid folders if they don't exist
os.makedirs(train_path, exist_ok=True)
os.makedirs(test_path, exist_ok=True)
os.makedirs(valid_path, exist_ok=True)

# Get the list of classes (subdirectories) in the dataset
classes = os.listdir(dataset_path)

# Iterate over each class
for class_name in classes:
    class_path = os.path.join(dataset_path, class_name)
    class_images = [os.path.join(class_path, img) for img in os.listdir(class_path)]

    # Split the images into training, testing, and validation sets
    train_images, temp_images = train_test_split(class_images, test_size=0.2, random_state=42)
    valid_images, test_images = train_test_split(temp_images, test_size=0.5, random_state=42)

    # Define the paths for the train, test, and valid sets for the current class
    train_class_path = os.path.join(train_path, class_name)
    test_class_path = os.path.join(test_path, class_name)
    valid_class_path = os.path.join(valid_path, class_name)

    # Create the train, test, and valid class folders if they don't exist
    os.makedirs(train_class_path, exist_ok=True)
    os.makedirs(test_class_path, exist_ok=True)
    os.makedirs(valid_class_path, exist_ok=True)

    # Copy images to their respective folders
    for img_path in train_images:
        shutil.copy(img_path, os.path.join(train_class_path, os.path.basename(img_path)))

    for img_path in test_images:
        shutil.copy(img_path, os.path.join(test_class_path, os.path.basename(img_path)))

    for img_path in valid_images:
        shutil.copy(img_path, os.path.join(valid_class_path, os.path.basename(img_path)))

In [ ]:
trainpath = '/content/train'
testpath = '/content/test'

In [ ]:
train_datagen = ImageDataGenerator(rescale = 1./255,zoom_range= 0.2,shear_range= 0.2)
test_datagen = ImageDataGenerator(rescale = 1./255)

In [ ]:
train = train_datagen.flow_from_directory(trainpath,target_size =(224,224),batch_size = 16)
test = test_datagen.flow_from_directory(testpath,target_size =(224,224),batch_size = 16)

Found 960 images belonging to 6 classes.
Found 120 images belonging to 6 classes.


## VGG 16

In [ ]:
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.models import Model

In [ ]:
vgg = VGG16(include_top = False,input_shape = (224,224,3))

58889256/58889256 [==============================] - 4s 0us/step


In [ ]:
for layer in vgg.layers:
  print(layer)

In [ ]:
len(vgg.layers)

19

In [ ]:
for layer in vgg.layers:
  layer.trainable = False

In [ ]:
x= Flatten()(vgg.output)

In [ ]:
output = Dense(6, activation ='softmax')(x)

In [ ]:
vgg16 = Model(vgg.input,output)

In [ ]:
vgg16.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0     

In [ ]:
from keras.optimizers import Adam
#opt = Adam(lr=0.001)

vgg16.compile(loss = 'categorical_crossentropy' , metrics =['accuracy'])

In [ ]:
from keras.optimizers import Adam
#opt = Adam(lr=0.001)
#model.compile(optimizer=opt, loss=keras.losses.categorical_crossentropy, metrics=['accuracy'])

In [ ]:
vgg16.fit(train,validation_data=test,epochs=10,steps_per_epoch=len(train),validation_steps =len(test))

Epoch 1/10
60/60 [==============================] - 40s 492ms/step - loss: 1.0540 - accuracy: 0.7281 - val_loss: 0.1382 - val_accuracy: 0.9583
Epoch 2/10
60/60 [==============================] - 29s 480ms/step - loss: 0.2369 - accuracy: 0.9219 - val_loss: 0.0997 - val_accuracy: 0.9583
Epoch 3/10
60/60 [==============================] - 29s 491ms/step - loss: 0.1544 - accuracy: 0.9531 - val_loss: 0.0950 - val_accuracy: 0.9583
Epoch 4/10
60/60 [==============================] - 28s 465ms/step - loss: 0.1183 - accuracy: 0.9635 - val_loss: 0.6423 - val_accuracy: 0.7833
Epoch 5/10
60/60 [==============================] - 25s 417ms/step - loss: 0.0698 - accuracy: 0.9760 - val_loss: 0.2270 - val_accuracy: 0.9500
Epoch 6/10
60/60 [==============================] - 24s 404ms/step - loss: 0.0587 - accuracy: 0.9823 - val_loss: 0.0627 - val_accuracy: 0.9667
Epoch 7/10
60/60 [==============================] - 26s 430ms/step - loss: 0.0495 - accuracy: 0.9833 - val_loss: 0.0417 - val_accuracy: 0.9833

In [ ]:
len(train)

60

In [ ]:
len(test)

8

## Resnet50

In [ ]:
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.models import Model

In [ ]:
resnet50 = ResNet50(include_top = False,input_shape = (224,224,3))

94765736/94765736 [==============================] - 5s 0us/step


In [ ]:
for layer in resnet50.layers:
  print(layer)

In [ ]:
len(resnet50.layers)

175

In [ ]:
for layer in resnet50.layers:
  layer.trainable = False

In [ ]:
x = Flatten()(resnet50.output)

In [ ]:
output = Dense(6,activation = 'softmax')(x)

In [ ]:
resnet50 =Model(resnet50.input,output)

In [ ]:
resnet50.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_2 (InputLayer)        [(None, 224, 224, 3)]        0         []                            
                                                                                                  
 conv1_pad (ZeroPadding2D)   (None, 230, 230, 3)          0         ['input_2[0][0]']             
                                                                                                  
 conv1_conv (Conv2D)         (None, 112, 112, 64)         9472      ['conv1_pad[0][0]']           
                                                                                                  
 conv1_bn (BatchNormalizati  (None, 112, 112, 64)         256       ['conv1_conv[0][0]']          
 on)                                                                                        

In [ ]:
resnet50.compile(loss = 'categorical_crossentropy',optimizer = 'adam',metrics =['accuracy'])

In [ ]:
resnet50.fit(train,validation_data=test,epochs=10,steps_per_epoch=len(train),validation_steps =len(test))

Epoch 1/10
60/60 [==============================] - 31s 431ms/step - loss: 4.5310 - accuracy: 0.3417 - val_loss: 1.7819 - val_accuracy: 0.5083
Epoch 2/10
60/60 [==============================] - 25s 416ms/step - loss: 1.2865 - accuracy: 0.5333 - val_loss: 1.4062 - val_accuracy: 0.5000
Epoch 3/10
60/60 [==============================] - 25s 409ms/step - loss: 1.3362 - accuracy: 0.5490 - val_loss: 2.4856 - val_accuracy: 0.5333
Epoch 4/10
60/60 [==============================] - 26s 427ms/step - loss: 1.2944 - accuracy: 0.5865 - val_loss: 1.4770 - val_accuracy: 0.5750
Epoch 5/10
60/60 [==============================] - 26s 426ms/step - loss: 1.2207 - accuracy: 0.6125 - val_loss: 1.5707 - val_accuracy: 0.6333
Epoch 6/10
60/60 [==============================] - 25s 416ms/step - loss: 1.2155 - accuracy: 0.6313 - val_loss: 0.9807 - val_accuracy: 0.6750
Epoch 7/10
60/60 [==============================] - 26s 427ms/step - loss: 1.0945 - accuracy: 0.6573 - val_loss: 1.6633 - val_accuracy: 0.5917

# save file .h5

In [ ]:
vgg16.save('cnn_final.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


# Testing the Data

In [ ]:
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
from tensorflow.keras.preprocessing.image import load_img, img_to_array

In [ ]:
labels=['Ammonites','Belemnites','Corals','Crinoids','Leaf fossils','Trilobites']

# Testing Class 1

In [ ]:
img_path ='/content/test/Ammonites/Ammonite104.jpg'

In [ ]:
import numpy as np
img = load_img(img_path, target_size=(224, 224))
x = img_to_array(img)
x = preprocess_input(x)
preds = vgg16.predict(np.array([x]))
preds

1/1 [==============================] - 1s 653ms/step


array([[1., 0., 0., 0., 0., 0.]], dtype=float32)

In [ ]:
labels[np.argmax(preds)]

'Ammonites'

# Testing Class 2

In [ ]:
img_path ='/content/test/Belemnites/Belemnite10.jpg'

In [ ]:
import numpy as np
img = load_img(img_path, target_size=(224, 224))
x = img_to_array(img)
x = preprocess_input(x)
preds = vgg16.predict(np.array([x]))
preds

1/1 [==============================] - 0s 19ms/step


array([[0., 1., 0., 0., 0., 0.]], dtype=float32)

In [ ]:
labels[np.argmax(preds)]

'Belemnites'

# Testing Class 3

In [ ]:
img_path ='/content/test/Corals/Coral122.jpg'

In [ ]:
import numpy as np
img = load_img(img_path, target_size=(224, 224))
x = img_to_array(img)
x = preprocess_input(x)
preds = vgg16.predict(np.array([x]))
preds

1/1 [==============================] - 0s 20ms/step


array([[0., 0., 1., 0., 0., 0.]], dtype=float32)

In [ ]:
labels[np.argmax(preds)]

'Corals'

# Testing Class 4

In [ ]:
img_path ='/content/test/Crinoids/Crinoid105.jpg'

In [ ]:
import numpy as np
img = load_img(img_path, target_size=(224, 224))
x = img_to_array(img)
x = preprocess_input(x)
preds = vgg16.predict(np.array([x]))
preds

1/1 [==============================] - 0s 17ms/step


array([[0., 0., 0., 1., 0., 0.]], dtype=float32)

In [ ]:
labels[np.argmax(preds)]

'Crinoids'

# Testing Class 5

In [ ]:
img_path ='/content/test/Leaf fossils/Leaf fossil1.jpg'

In [ ]:
import numpy as np
img = load_img(img_path, target_size=(224, 224))
x = img_to_array(img)
x = preprocess_input(x)
preds = vgg16.predict(np.array([x]))
preds

1/1 [==============================] - 0s 20ms/step


array([[0.0000000e+00, 4.1035190e-02, 9.5896482e-01, 0.0000000e+00,
        2.5817816e-35, 0.0000000e+00]], dtype=float32)

In [ ]:
labels[np.argmax(preds)]

'Corals'

# Testing Class 6

In [ ]:
img_path ='/content/test/Trilobites/Trilobite109.jpg'

In [ ]:
import numpy as np
img = load_img(img_path, target_size=(224, 224))
x = img_to_array(img)
x = preprocess_input(x)
preds = vgg16.predict(np.array([x]))
preds

1/1 [==============================] - 0s 20ms/step


array([[0., 0., 0., 0., 0., 1.]], dtype=float32)

In [ ]:
labels[np.argmax(preds)]

'Trilobites'

In [ ]:
import shutil

# Replace 'source_folder' with the path of the folder you want to zip
source_folder = '/content/test'

# Replace 'output_zip_file.zip' with the desired name of the zip file
output_zip_file = '/content/test.zip'

# Create a zip file from the folder
shutil.make_archive(output_zip_file.replace('.zip', ''), 'zip', source_folder)


'/content/test.zip'

In [ ]:
import shutil

# Replace 'source_folder' with the path of the folder you want to zip
source_folder = '/content/valid'

# Replace 'output_zip_file.zip' with the desired name of the zip file
output_zip_file = '/content/valid'

# Create a zip file from the folder
shutil.make_archive(output_zip_file.replace('.zip', ''), 'zip', source_folder)

'/content/valid.zip'

In [ ]:
import shutil

# Replace 'source_folder' with the path of the folder you want to zip
source_folder = '/content/train'

# Replace 'output_zip_file.zip' with the desired name of the zip file
output_zip_file = '/content/train'

# Create a zip file from the folder
shutil.make_archive(output_zip_file.replace('.zip', ''), 'zip', source_folder)

'/content/train.zip'